# Site settings
title: "Changeling the Podcast"
description: "A podcast for the roleplaying game Changeling the Podcast"
podcast-description: "Your hosts Pooka and Josh give book reviews, interviews, and all sorts of interesting information about Changeling the Dreaming"
url:  "https://changelingthepodcast.com" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Joshua Hillerup and Pooka Gar"
  email: "podcast"
permalink: /:title
keywords: [podcast, changeling]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: ChangelingCast
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Joshua Hillerup and Pooka Gar
  links:
lang: en
